# Generated by Django 4.1.2 on 2022-10-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.BigIntegerField()),
                ('nombre_empleado', models.CharField(max_length=256)),
                ('fecha_de_contratacion', models.DateField(auto_now_add=True)),
                ('RFC', models.CharField(max_length=256)),
                ('hora_entrada', models.CharField(default='%H:%M:%S', max_length=50)),
                ('hora_salida', models.CharField(default='%H:%M:%S', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='piezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=256)),
                ('estado', models.CharField(max_length=256)),
            ],
        ),
    ]
