# Generated by Django 4.1.2 on 2022-10-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='fecha_de_contratacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='hora_entrada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='hora_salida',
            field=models.TimeField(),
        ),
    ]
